import Anthropic from '@anthropic-ai/sdk';
import { askClaude } from './anthropic';
import { buildSystemPrompt, type SystemPromptBlock } from './prompts';
import { checkAndCount, type RateLimitStore } from './rate-limit';
import { corsHeaders, handlePreflight } from './cors';
import { signCookie, verifyCookie, parseCookie, newSessionId } from './cookie';

// Bundled content — generated by scripts/build-content.mjs into src/content.json
import content from './content.json';
const { factsYaml, agentBrief, toneGuide, projects } = content as {
  factsYaml: string;
  agentBrief: string;
  toneGuide: string;
  projects: string[];
};

export interface Env {
  ANTHROPIC_API_KEY: string;
  SESSION_COOKIE_SECRET: string;
  ALLOWED_ORIGIN: string;
  RATE_LIMIT_PER_HOUR: string;
  MAX_INPUT_CHARS: string;
  MAX_OUTPUT_TOKENS: string;
  RATE_LIMIT_KV: KVNamespace;
}

const FALLBACK_CONTACTS = {
  email: 'niv@schendel.me',
  linkedin: 'https://linkedin.com/in/niv-schendel',
};

export default {
  async fetch(request: Request, env: Env, _ctx: ExecutionContext): Promise<Response> {
    const allowedOrigin = env.ALLOWED_ORIGIN;
    const reqOrigin = request.headers.get('Origin');

    if (request.method === 'OPTIONS') {
      return handlePreflight(request, allowedOrigin);
    }

    if (reqOrigin !== allowedOrigin) {
      return new Response('Forbidden', { status: 403 });
    }

    if (request.method !== 'POST') {
      return new Response('Method not allowed', { status: 405 });
    }

    const cors = corsHeaders(reqOrigin, allowedOrigin);

    // Parse and validate body
    let body: { messages?: Array<{ role: string; content: string }> };
    try {
      body = await request.json();
    } catch {
      return json({ error: 'input_invalid', reason: 'non_text' }, 400, cors);
    }
    const messages = body.messages ?? [];
    const lastUser = [...messages].reverse().find((m) => m.role === 'user');
    if (!lastUser || !lastUser.content.trim()) {
      return json({ error: 'input_invalid', reason: 'empty' }, 400, cors);
    }
    const maxChars = parseInt(env.MAX_INPUT_CHARS, 10);
    if (lastUser.content.length > maxChars) {
      return json({ error: 'input_invalid', reason: 'too_long' }, 400, cors);
    }

    // Resolve session cookie
    const cookieHeader = request.headers.get('Cookie');
    const signed = parseCookie(cookieHeader, 'session');
    let sessionId = signed ? await verifyCookie(signed, env.SESSION_COOKIE_SECRET) : null;
    let setCookieHeader: string | null = null;
    if (!sessionId) {
      sessionId = newSessionId();
      const newSigned = await signCookie(sessionId, env.SESSION_COOKIE_SECRET);
      setCookieHeader = `session=${newSigned}; Domain=chat.niv.schendel.me; HttpOnly; Secure; SameSite=Lax; Max-Age=86400; Path=/`;
    }

    // Rate limit
    const ip = request.headers.get('CF-Connecting-IP') ?? 'unknown';
    const store: RateLimitStore = {
      get: async (k) => {
        const v = await env.RATE_LIMIT_KV.get(k);
        return v ? JSON.parse(v) : null;
      },
      put: async (k, v) => {
        await env.RATE_LIMIT_KV.put(k, JSON.stringify(v), { expirationTtl: 3600 });
      },
    };
    const limit = parseInt(env.RATE_LIMIT_PER_HOUR, 10);
    const rl = await checkAndCount(store, `ip:${ip}`, `cookie:${sessionId}`, limit, 3600);
    if (!rl.allowed) {
      return json(
        {
          error: 'rate_limit',
          retryAfterSeconds: rl.retryAfterSeconds,
          fallbackContacts: FALLBACK_CONTACTS,
        },
        429,
        { ...cors, ...maybeCookieHeader(setCookieHeader) },
      );
    }

    // Build prompt and call Claude
    const systemBlocks: SystemPromptBlock[] = buildSystemPrompt({
      factsYaml,
      agentBrief,
      toneGuide,
      projects,
    });

    const client = new Anthropic({ apiKey: env.ANTHROPIC_API_KEY });
    let reply: string;
    try {
      reply = await askClaude(client, {
        systemBlocks,
        messages: messages.map((m) => ({
          role: m.role as 'user' | 'assistant',
          content: m.content,
        })),
        maxTokens: parseInt(env.MAX_OUTPUT_TOKENS, 10),
      });
    } catch (e) {
      console.error('Anthropic error', e);
      return json({ error: 'internal' }, 500, { ...cors, ...maybeCookieHeader(setCookieHeader) });
    }

    return json(
      {
        reply,
        remainingQuota: rl.remaining,
        language: detectLanguage(reply),
      },
      200,
      { ...cors, ...maybeCookieHeader(setCookieHeader) },
    );
  },
} satisfies ExportedHandler<Env>;

function json(body: unknown, status: number, headers: Record<string, string>): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'Content-Type': 'application/json', ...headers },
  });
}

function maybeCookieHeader(setCookie: string | null): Record<string, string> {
  return setCookie ? { 'Set-Cookie': setCookie } : {};
}

function detectLanguage(text: string): 'en' | 'he' | 'mixed' {
  const hebrew = /[א-ת]/.test(text);
  const latin = /[A-Za-z]/.test(text);
  if (hebrew && latin) return 'mixed';
  if (hebrew) return 'he';
  return 'en';
}
